nav:
  Home: /
  About: /about/
  Writing: /archives/
  Portfolio: /portfolio/
  Mixtapes: /mixtapes/
  Gallery: /gallery/gallery.html

projects_url: http://github.com/paulpod

customize:
    gravatar:
        email: 
    logo:
        enabled: true
        width: 50
        height: 50
        url: /images/logo.png
        gravatar: false
    favicon: 
      # eg. generate with http://realfavicongenerator.net/
      desktop:
        url: /images/favicon.ico
        gravatar: false
      android:
        url: /images/favicon-192x192.png
        gravator: false
      apple:
        url: /images/apple-touch-icon.png
        gravator: false
    social_links:
        github: http://github.com/paulpod
        instagram: http://instagram.com/paulpod
        twitter: http://twitter.com/paulpod
        linkedin: https://www.linkedin.com/in/paulpod/
        mastodon: https://mastodon.cloud/web/accounts/7288
    show_all_posts: false
    post_count: 10
    highlight: pojoaque

# RSS
rss: false

# Plugins
plugins:
    disqus_shortname: # Disqus Comments Shortname
    google_analytics: UA-40641766-1 # enter the tracking ID for your Google Analytics


# Miscellaneous
miscellaneous:
    open_graph: # see http://ogp.me
        fb_app_id:
        fb_admins:
        twitter_id:
        google_plus:
